# Generated by Django 4.0.3 on 2022-03-31 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('timer', models.IntegerField(default=5)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-timeStamp',),
            },
        ),
        migrations.CreateModel(
            name='Servay_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=1000)),
                ('question_type', models.CharField(choices=[('text', 'text'), ('radio', 'radio'), ('multiple', 'multiple')], default='text', max_length=250)),
                ('survay_of_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survay_of_question', to='survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='question_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=500)),
                ('survay_of_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survay_of_option', to='survey.survey')),
                ('survey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='survey.servay_question')),
                ('voter', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
