# Generated by Django 4.0.3 on 2022-04-02 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_survey_attendant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question_options',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='attendant_user',
        ),
    ]
