# Generated by Django 4.0.3 on 2022-04-01 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0002_survey_attendant_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('survey_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suervy_info', to='survey.survey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveyor_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('text', 'text'), ('radio', 'radio'), ('multiple', 'multiple')], max_length=50)),
                ('option_answer', models.ManyToManyField(related_name='option_from', to='survey.question_options')),
                ('question_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_from', to='survey.servay_question')),
                ('survey_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_from', to='survey_record.surveyinfo')),
            ],
        ),
    ]
