# Generated by Django 4.0.3 on 2022-04-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyinfo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
