# Generated by Django 4.0.3 on 2022-04-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_question_options_voter_and_more'),
        ('survey_record', '0002_alter_surveyinfo_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='option_answer',
            field=models.ManyToManyField(blank=True, related_name='option_from', to='survey.question_options'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='text_answer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
