# Generated by Django 4.0.3 on 2022-04-04 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_record', '0003_alter_questionanswer_option_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionanswer',
            old_name='survey_from',
            new_name='from_survey',
        ),
    ]
