# Generated by Django 4.0.3 on 2022-04-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_record', '0004_rename_survey_from_questionanswer_from_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='question_type',
            field=models.CharField(blank=True, choices=[('text', 'text'), ('radio', 'radio'), ('multiple', 'multiple')], max_length=50, null=True),
        ),
    ]
