# Generated by Django 4.0.3 on 2022-04-04 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_question_options_voter_and_more'),
        ('survey_record', '0005_alter_questionanswer_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='from_survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_from', to='survey_record.surveyinfo'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='option_answer',
            field=models.ManyToManyField(blank=True, null=True, related_name='option_from', to='survey.question_options'),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_from', to='survey.servay_question'),
        ),
    ]
